---
title: poems
author: ''
date: ''
slug: poems
categories: []
tags: []
disable_comments: yes
---

<style type="text/css">
body { counter-reset: poems; }
h2::before { counter-increment: poems; content: counter(poems) ". "; }
</style>

平时读到一些有意思的句子就会贴到到手机里存着，把多年攒的句子放在这个页面。

有诗歌也有单个句子，并没有考究出处。

有的可能比较中二，年代有点久远。

年轻时候谁不中二一点。

> 词以境界为最上。有境界则自成高格，自有名句。五代北宋之词，所以独绝者在此。
> 
> 有造境，有写境，此理想与写实二派之所由分。然二者颇难分别。因大诗人所造之境，必合乎自然，所写之境，亦必邻于理想故也。
> 
> —王国维，《人间词话》 

<center>
<font face="楷体">


## 摸鱼儿·雁丘词 / 迈陂塘·雁丘词

金 · [元好问](https://so.gushiwen.cn/authorv_87bdc6fea2cb.aspx)

__问世间，情为何物，直教生死相许？__
天南地北双飞客，老翅几回寒暑。
欢乐趣，离别苦，就中更有痴儿女。
君应有语：
__渺万里层云，千山暮雪，只影向谁去？__

横汾路，寂寞当年箫鼓，荒烟依旧平楚。
招魂楚些何嗟及，山鬼暗啼风雨。
天也妒，未信与，莺儿燕子俱黄土。
千秋万古，为留待骚人，狂歌痛饮，来访雁丘处。


## 戏为六绝句（其二）

唐 · [杜甫](https://so.gushiwen.cn/authorv_515ea88d1858.aspx)

王杨卢骆当时体，轻薄为文哂未休。

__尔曹身与名俱灭，不废江河万古流。__

## 水龙吟·登建康赏心亭 

宋 · [辛弃疾](https://so.gushiwen.cn/authorv_a7900666497f.aspx)

楚天千里清秋，水随天去秋无际。遥岑远目，献愁供恨，玉簪螺髻。落日楼头，断鸿声里，江南游子。把吴钩看了，栏杆拍遍，无人会，登临意。

休说鲈鱼堪脍，尽西风，季鹰归未？求田问舍，怕应羞见，刘郎才气。可惜流年，忧愁风雨，树犹如此！倩何人唤取，红巾翠袖，揾英雄泪？

## 登华岳南峰极顶七绝

清 · [牛兆濂](https://www.mingyantong.com/writer/586330)

踏破白云千万重，仰天池上水溶溶。

__横空大气排山去，砥柱人间是此峰。__

## 临江仙·夜饮东坡醒复醉 

宋 · [苏轼](https://hanyu.baidu.com/s?wd=%E8%8B%8F%E8%BD%BC)

夜饮东坡醒复醉，归来仿佛三更。家童鼻息已雷鸣。敲门都不应，倚杖听江声。

长恨此身非我有，何时忘却营营。夜阑风静縠纹平。
__小舟从此逝，江海寄余生。__


## 嫦娥 

唐 · [李商隐](https://so.gushiwen.org/authorv_bc94c92721b8.aspx)

云母屏风烛影深，长河渐落晓星沉。
嫦娥应悔偷灵药，碧海青天夜夜心。

## 哭晁卿衡

唐 · [李白](https://so.gushiwen.org/authorv_b90660e3e492.aspx)

日本晁卿辞帝都，征帆一片绕蓬壶。

明月不归沉碧海，白云愁色满苍梧。


## 酬乐天咏老见示 

唐 · [刘禹锡](https://so.gushiwen.org/authorv_e3c4e8cf2646.aspx)

人谁不顾老，老去有谁怜。

身瘦带频减，发稀冠自偏。

废书缘惜眼，多炙为随年。

经事还谙事，阅人如阅川。

细思皆幸矣，下此便翛然。

__莫道桑榆晚，为霞尚满天。__


## 咏怀古迹五首·其一

唐 · [杜甫](https://so.gushiwen.org/search.aspx?value=%E6%9D%9C%E7%94%AB)

支离东北风尘际，漂泊西南天地间。

三峡楼台淹日月，五溪衣服共云山。

羯胡事主终无赖，词客哀时且未还。

__庾信平生最萧瑟，暮年诗赋动江关。__


## 卜算子.赠妓

宋 · [谢希孟](https://www.gushiwen.org/GuShiWen_3089361c40.aspx)

双桨浪花平，夹岸青山锁。你自归家我自归，说着如何过？ 

我断不思量，你莫思量我。将你从前与我心，付与他人可！


## 走笔谢孟谏议寄新茶

唐 · [卢仝](https://hanyu.baidu.com/s?wd=%E5%8D%A2%E4%BB%9D)

日高丈五睡正浓，军将打门惊周公。
口云谏议送书信，白绢斜封三道印。
开缄宛见谏议面，手阅月团三百片。
闻道新年入山里，蛰虫惊动春风起。
天子须尝阳羡茶，百草不敢先开花。
仁风暗结珠琲瓃，先春抽出黄金芽。
摘鲜焙芳旋封裹，至精至好且不奢。
至尊之馀合王公，何事便到山人家。
柴门反关无俗客，纱帽笼头自煎吃。
碧云引风吹不断，白花浮光凝碗面。
一碗喉吻润，两碗破孤闷。
三碗搜枯肠，唯有文字五千卷。
四碗发轻汗，平生不平事，尽向毛孔散。
五碗肌骨清，六碗通仙灵。七碗吃不得也，唯觉两腋习习清风生。
蓬莱山，在何处。玉川子，乘此清风欲归去。
山上群仙司下土，地位清高隔风雨。
安得知百万亿苍生命，堕在巅崖受辛苦。
便为谏议问苍生，到头还得苏息否。


## 望江南·超然台作 

宋 · [苏轼](https://hanyu.baidu.com/s?wd=%E8%8B%8F%E8%BD%BC)

春未老，风细柳斜斜。试上超然台上望，半壕春水一城花。烟雨暗千家。

寒食后，酒醒却咨嗟。休对故人思故国，且将新火试新茶。__诗酒趁年华。__


## 卜算子·黄州定慧院寓居作 

宋 · [苏轼](https://hanyu.baidu.com/s?wd=%E8%8B%8F%E8%BD%BC)

缺月挂疏桐，漏断人初静。__谁见幽人独往来，缥缈孤鸿影。__

惊起却回头，有恨无人省。拣尽寒枝不肯栖，寂寞沙洲冷。


## 浣溪沙·细雨斜风作晓寒 

宋 · [苏轼](https://hanyu.baidu.com/s?wd=%E8%8B%8F%E8%BD%BC)

细雨斜风作晓寒，淡烟疏柳媚晴滩。入淮清洛渐漫漫。

雪沫乳花浮午盏，蓼茸蒿笋试春盘。__人间有味是清欢。__


## 定风波·南海归赠王定国侍人寓娘 

宋 · [苏轼](https://hanyu.baidu.com/s?wd=%E8%8B%8F%E8%BD%BC)

__常羡人间琢玉郎。天应乞与点酥娘。__ 尽道清歌传皓齿。风起。雪飞炎海变清凉。

万里归来颜愈少。微笑。笑时犹带岭梅香。 __试问岭南应不好。却道。此心安处是吾乡。__

## 临江仙·送钱穆父 

宋 · [苏轼](https://hanyu.baidu.com/s?wd=%E8%8B%8F%E8%BD%BC)

一别都门三改火，天涯踏尽红尘。依然一笑作春温。无波真古井，有节是秋筠。

惆怅孤帆连夜发，送行淡月微云。尊前不用翠眉颦。__人生如逆旅，我亦是行人。__


## 临江仙·梦后楼台高锁 

宋 · [晏几道](https://hanyu.baidu.com/s?wd=%E6%99%8F%E5%87%A0%E9%81%93)

梦后楼台高锁，酒醒帘幕低垂。去年春恨却来时。__落花人独立，微雨燕双飞。__

记得小苹初见，两重心字罗衣。琵琶弦上说相思。__当时明月在，曾照彩云归。__


## 鹧鸪天·林断山明竹隐墙 

宋 · [苏轼](https://hanyu.baidu.com/s?wd=%E8%8B%8F%E8%BD%BC)

林断山明竹隐墙。乱蝉衰草小池塘。翻空白鸟时时见，照水红蕖细细香。

村舍外，古城旁。杖藜徐步转斜阳。__殷勤昨夜三更雨，又得浮生一日凉。__


## 减字木兰花·莺初解语 

宋 · [苏轼](https://hanyu.baidu.com/s?wd=%E8%8B%8F%E8%BD%BC)

莺初解语。最是一年春好处。微雨如酥。草色遥看近却无。

休辞醉倒。花不看开人易老。莫待春回。颠倒红英间绿苔。


## 定风波·莫听穿林打叶声

宋 · [苏轼](https://hanyu.baidu.com/s?wd=%E8%8B%8F%E8%BD%BC)

三月七日，沙湖道中遇雨。雨具先去，同行皆狼狈，余独不觉。已而遂晴，故作此词。

莫听穿林打叶声，何妨吟啸且徐行。__竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。__

料峭春风吹酒醒，微冷，山头斜照却相迎。回首向来萧瑟处，归去，也无风雨也无晴。

## 行女哀辞

两汉 · [曹植](https://so.gushiwen.org/authorv_6c695909f577.aspx)

序：行女生于季秋，而终于首夏。三年之中，二子频丧。

伊上帝之降命，何修短之难哉；

或华发以终年，或怀妊而逢灾。

感前哀之未阕，复新殃之重来！

方朝华而晚敷，比晨露而先晞。

感逝者之不追，情忽忽而失度。


## 金缕衣

唐 · 无名氏

__劝君莫惜金缕衣，劝君惜取少年时。__

花开堪折直须折，莫待无花空折枝。


## 上李邕 

唐 · [李白](https://hanyu.baidu.com/s?wd=%E6%9D%8E%E7%99%BD)

__大鹏一日同风起，扶摇直上九万里。__

假令风歇时下来，犹能簸却沧溟水。

世人见我恒殊调，闻余大言皆冷笑。

宣父犹能畏后生，丈夫未可轻年少。


## **梦天** 

唐 · [李贺](https://m.gushiwen.org/authorv_74d46d599f15.aspx)

老兔寒蟾泣天色，云楼半开壁斜白。

玉轮轧露湿团光，鸾珮相逢桂香陌。

黄尘清水三山下，更变千年如走马。

__遥望齐州九点烟，一泓海水杯中泻。__



## 杂曲歌辞·踏歌词

唐代 · [张说](https://so.gushiwen.org/authorv_e47835478657.aspx)

花萼楼前雨露新，长安城里太平人。

龙衔火树千灯艳，鸡踏莲花万岁春。

帝宫三五戏春台，行雨流风莫妒来。

西域灯轮千影合，东华金阙万重开。

## 和贾舍人早朝大明宫之作

唐代 · [王维](https://so.gushiwen.org/authorv_52fceee85532.aspx)

绛帻鸡人送晓筹，尚衣方进翠云裘。

九天阊阖开宫殿，万国衣冠拜冕旒。

日色才临仙掌动，香烟欲傍衮龙浮。

朝罢须裁五色诏，佩声归向凤池头。


## 登观音台望城

唐代 · [白居易](https://so.gushiwen.org/authorv_85097dd0c645.aspx)

百千家似围棋局，十二街如种菜畦。

遥认微微入朝火，一条星宿五门西。

## 长相思·其一

唐代 · [李白]()

长相思，在长安。

络纬秋啼金井阑，微霜凄凄簟色寒。

孤灯不明思欲绝，卷帷望月空长叹。

美人如花隔云端！

上有青冥之长天，下有渌水之波澜。

天长路远魂飞苦，梦魂不到关山难。

长相思，摧心肝！


## 引驾行·红尘紫陌

宋 · [柳永](https://so.gushiwen.org/authorv_682bdf0fd34e.aspx)

红尘紫陌，斜阳暮草长安道，是离人。断魂处，迢迢匹马西征。新晴。韶光明媚，轻烟淡薄和气暖，望花村。路隐映，摇鞭时过长亭。愁生。伤凤城仙子，别来千里重行行。又记得、临歧泪眼，湿莲脸盈盈。
消凝。花朝月夕，最苦冷落银屏。想媚容、耿耿无眠，屈指已算回程。相萦。空万般思忆，争如归去睹倾城。向绣帏、深处并枕，说如此牵情。


## 望海潮·东南形胜

宋 · [柳永](https://so.gushiwen.org/authorv_682bdf0fd34e.aspx)

东南形胜，三吴都会，钱塘自古繁华。

烟柳画桥，风帘翠幕，参差十万人家。

云树绕堤沙，怒涛卷霜雪，天堑无涯。

市列珠玑，户盈罗绮，竞豪奢。

重湖叠巘清嘉。有三秋桂子，十里荷花。

羌管弄晴，菱歌泛夜，嬉嬉钓叟莲娃。

千骑拥高牙。乘醉听箫鼓，吟赏烟霞。

异日图将好景，归去凤池夸。



=======================非古诗词=======================

## 仓央嘉措

跨鹤高飞意壮哉，云霄一羽雪皑皑。

此行莫恨天涯远，咫尺理塘归去来。


## 泛舟厦门海

来自网络

天高海阔水无垠，浮玉明珠满目陈。望眼金门终不远，回身鹭岛已成邻。

云舟破浪翻新页，鸥鸟飞身引故人。一片霞光铺两岸，千帆竞发接新晨。


## 摘自《水浒传》

作者:[施耐庵](https://www.mingyantong.com/ju/258127)

莫语常言道知足，万事至终总是空。

理想现实一线隔，心无旁骛脚踏实。

__谁无暴风劲雨时，守得云开见月明。__

花开复见却飘零，残憾莫使今生留。

</center>

<center>
## 来自[网络](https://www.douban.com/note/239227888/)
</center>

尘寰外，碧海中，桃花之间桃花岛。
秋风起，海波兴，几度潮来听玉箫。
箫声起处落英飞，遽引心情向碧霄。
桃花纷飞诉往事，风中烟柳叶飘摇。
相逢本是瑶池间，盈盈花开芙蓉仙。
芙蓉仙子织涟漪，油壁香车待鲜妍。
蓬莱三山固所道，亦羡人间好情缘。
从此千里不独行，侠义江湖同仗剑。
未必女流让须眉，兰心蕙质更比肩。
博闻强记天下事，九阴真经只等闲。
九阴又何贵?九阴竟使君命违。
明日峰前再论剑，相伴华山知者谁？
由来文字与武功，未如心意双高飞。
十年不得慕红颜，敢笑唐皇与杨妃。
梦时抚琴商转徵，丁香愁肠枉自悲。
梧桐故事漫嗟呀，细把云烟裁作纱。
一处杜鹃悄无语，一处萧萧半白发。
七月七日梦天桥，闻道君思寄桃花？
若无鸿雁奉鱼书，还叫无常带句话。
我于浊世间，君在黄泉下，
相忆相依两无期，相思何事纪年华!
碧海潮起天地惊，碧海潮落鬼神泣。
碧海桃花之精英，凝于碧海潮生曲。
此曲一出奋鹰扬，能使妖魔胆尽丧。
弹指一挥风波起，太虚蹑后步天罡。
再吟此曲凋日月，纷纷四海大浪张。
世人未谙碧海意，尽道此潮最泱泱。
不知潮起潮落间，碧海一曲为君飨。
桃花飞殇哀往事，曲尽碧海尚彷徨。

<center> 
## 来自网络 
</center>

- 最孤独的人最亲切,受过伤的人总是笑的最灿烂,因为他们不愿让身边的人承受一样的痛苦。…韩国电影素媛
- 一朝时运至，半点不由人。(来自兰陵笑笑生《金瓶梅》)
- (第七十五回) 人生世上风波险，一日风波十二时。(来自兰陵笑笑生《金瓶梅》)
- 审格局，决一世之荣枯； 观气色，定行年之休咎。(来自网络，新金瓶梅)
- 命里有时终须有，命里无时莫强求。(出自《金瓶梅》第十四回。也见《增广贤文》(上集))
- 天下风云出我辈， 一入江湖岁月催； 
皇图霸业谈笑间， 不胜人生一场醉。 
提剑跨骑挥鬼雨， 白骨如山鸟惊飞; 
尘事如潮人如水， 只叹江湖几人回。(来自徐克的电影：笑傲江湖二之东方不败)
- 来自网络:
长相思，在长安。^[李白的长相思·其一] 
百千家似围棋局，十二街如种菜畦。^[白居易的登观音台望城] 
九天阊阖开宫殿，万国衣冠拜冕旒。^[王维的和贾舍人早朝大明宫之作] 
西域灯轮千影合，东华金阙万重开。^[张说的杂曲歌辞·踏歌词] 
长安道，是离人。^[柳永的引驾行·红尘紫陌] 
- 来自网络 :“凡是过去，皆为序章”（What’s past is prologue）， 这句话出自于莎士比亚戏剧《暴风雨》中。
《暴风雨》写于1611年，是莎士比亚的最后一部“传奇剧”。《暴风雨》描写了米兰公爵普洛斯彼罗被弟弟安东尼奥夺去爵位，带着女儿米兰达和魔术书流亡到一座荒岛，在那里调遣精灵，呼风唤雨。而“凡是过去，皆为序章”这句话出现在第二幕第一场中，出自弟弟安东尼奥之口。在该剧的译本中，这句话也被译作“以往的一切都只是个开场的引子”或“以往的只算得是序幕”。
- 来自网络:美国著名乡村歌手夫妻，约翰尼·凯什和琼·卡特，是美国乐坛的金童玉女，彼此非常恩爱。其中凯什在妻子卡特65岁生日时写给妻子的情书（1994年），是许多人都研读过的经典美文：
“我们渐渐变老，也早已习惯了彼此。我们想法一致、灵魂互通。无需询问我们便知道对方想要什么。偶尔我们也会惹对方不高兴，但那或许是因为我们真正把对方视作了理所当然的伴侣。有时候比如今天，我沉思之后意识到，能够与你这样一个我所见过的最伟大的女人共度余生，我是多么的幸运。”



>我遇见你，我记得你，这座城市天生适合恋爱，你天生适合我的灵魂。
>
>—杜拉斯

>我永恒的灵魂，注视着你的心
纵然黑夜孤寂，白昼如焚
>
>— 兰波

>我的爱情笨拙，如灌木，开出甜俗的花。

>后海有树的院子
>夏代有工的玉
>此时此刻的云
>二十来岁的你
>
>—冯唐

>与君初相识，犹如故人归。

>老来多健忘，唯不忘相思。

>风尘仆仆，终有归途。

>只要想起一生中后悔的事，梅花便落满了南山。
>
>—张枣

>你要爱荒野上的风声,胜过爱贫穷和思考

>浮云吹作雪，世味煮成茶。

>我见青山多妩媚，料青山见我应如是。

>你说人生如梦，我说人生如秀。
>
>—《再度重逢》

>我拥有的都是侥幸啊，我失去的都是人生。
>
>—《关于我爱你》

>风花雪月不肯等人，要献就献吻。
>
>—《夕阳无限好》

>七月在野，八月在宇，九月在户，十月蟋蟀，入我床下。
>
>—《诗经》

>暮冬时烤雪，迟夏写长信，早春不过一棵树。
>
>—陈鸿宇《途中》

>你是你的沧海一粟,你是你的万千可能之一种

>爱之于我，不是肌肤之亲，不是一蔬一菜，它是一种不死的欲望，是疲惫生活中的英雄梦想。
>
>—杜拉斯

>若逢新雪初霁 满月当空 下面平铺着皓影 上面流转着亮银 而你带笑地向我走来 月色和雪色之间 你是第三种绝色 
>
>—余光中

>与君初相识，犹如故人归。天涯明月新，朝暮最相思 
>
>—民国烟草广告

>浮世万千，挚爱有三，喷薄朝阳，皓婉皎月，不及汝尔，沧海桑田。
>
>I love three things in this world ，sun for morning ，moon for night ，and you forever
>
>— 翻译自《暮光之城》 

>我曾踏月而来，只因你在山中。
>
>—席慕蓉《山月》

>南有乔木，不可休思，汉有游女，不可求思。 
>
>—《诗经-汉广》

>绸缪束薪，三星在天。今夕何夕，见此良人。子兮子兮，如此良人何。
>
>—《诗经-国风》

>皎皎白驹，在彼空谷。生刍一束，其人如玉。毋金玉尔音，而有遐心。
>
> —《诗经-小雅》

> 今夜我不关心人类，我只想你。
>
> —海子《姐姐，今夜我在德令哈》

>所有人都闭着眼，我偷偷转头看你的侧脸，灯光温柔倾泻，
>
>而我只愿岁月不再轮回，时间不再流转。 
>
> —这是一段故事


>他教我，收余恨、免娇嗔，且自新、改性情，休恋逝水，苦海回身，早悟兰因。
>
>—京剧《锁麟囊》 


>湛湛青天不可欺，是非善恶人尽知；血海的冤仇终需报，且看来早与来迟。
>
>—京剧《徐策跑城》 


>这诗稿，不想它玉堂金马登高第，只望它高山流水遇知音。
>
>—越剧《红楼梦·焚稿》 

>一个儿抱膝舒怀，口儿里念着我；一个儿手托香腮，心儿里想着我；一个儿眼倦开，朦胧的觑看我；惟有布袋罗汉笑呵呵，他笑我时儿错，光阴过。
>
>—昆曲《孽海记·思凡》 


>唱不尽兴亡梦幻，弾不尽悲伤感叹，大古里凄凉满眼对江山。
>
>—昆曲《长生殿·弹词》 


>等得那，夏雨过、秋风起，等得那，长空雁叫断肠声。
>
>—越剧《陆游与唐婉》 

>但恨佳人难再得，岂知倾国与倾城！
>
>—昆曲《长生殿·哭像》 

>东风沉醉黄藤酒，往事如烟不可追。
>
>—越剧《陆游与唐婉》 


>笑的是，你瞒我、我瞒你，错过青春无处寻。
>
>—越剧《玉蜻蜓·前游庵》 

>第一碗白鲞红炖天堂肉，第二碗油煎鱼儿扑鼻香；第三碗香蕈蘑菇炖豆腐，第四碗白菜香干炒千张；第五碗酱烧胡桃浓又浓，第六碗酱油花椒醉花生
>
>—越剧《何文秀》  


>去时陌上花似锦，今日楼头柳又青。
>
>—京剧《春闺梦》

>为众人抱火者， 不可使他冻毙于风雪！
>
>为自由开路者， 不可使他困顿于荆棘！

> 中年以后的男人，时常会觉得孤独，因为他一睁开眼睛，周围都是要依靠他的人，却没有他可以依靠的人。
>
> —张爱玲




> 我曾踏足山巅，也曾进入低谷，二者都让我受益良多
>
> —LOL宝石骑士塔里克


>人生如逆旅 此心安处是吾乡 诗酒趁年华 江海寄余生 人间有味是清欢
>
>明月曾照彩云归 小舟寄江海
>
>人间有味是清欢 诗酒趁年华
>
>风起。雪飞炎海变清凉。却道。此心安处是吾乡。


</font>


> 虽然我不能陪你上九天揽月，但我可以陪你下海底捞肥牛捞毛肚捞虾滑捞黄喉捞鸭肠捞羊肉捞猪脑捞面筋捞豆腐捞青菜捞金针菇捞土豆捞脆皮肠捞鱼片捞莲藕




